package m6;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.ByteArraySerializer;
import org.apache.kafka.common.serialization.IntegerSerializer;

import java.util.Properties;

public class ProtobufBasicProducer {

    public static void main(String[] args) throws Exception {

        var userId = 123124;
        var pickUpPoint = "48.2026,16.3688";
        var dropOffPoint = "48.1869,16.3133";

        // TODO 1: Create a TripIntent object using class automatically generated by protoc

        var props = new Properties();
        props.setProperty("bootstrap.servers", "localhost:9092");
        props.setProperty("key.serializer", IntegerSerializer.class.getName());

        // TODO 3: Choose the right serializer

        // TODO 2: Adjust the type parameters for KafkaProducer and ProducerRecord
        KafkaProducer<Integer, String> producer = new KafkaProducer(props);

        // TODO 4: Convert TripIntent to bytes before sending
        ProducerRecord<Integer, String> r = new ProducerRecord<>("trip-intent", userId,
                "CHANGE_ME");
        producer.send(r).get();
    }
}
