version: "3.7"
services:
  zookeeper1:
    build: zookeeper
    environment:
      SERVER_ID: 1
  zookeeper2:
    build: zookeeper
    environment:
      SERVER_ID: 2
  zookeeper3:
    build: zookeeper
    environment:
      SERVER_ID: 3
  kafka1:
    build: kafka
    environment:
      BROKER_ID: 1
    ports:
      - 9091:9091
  kafka2:
    build: kafka
    environment:
      BROKER_ID: 2
    ports:
      - 9092:9092
  kafka3:
    build: kafka
    environment:
      BROKER_ID: 3
    ports:
      - 9093:9093
